todo-aspnetmvc-ui/ViewComponents/TodoListsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using todo_aspnetmvc_ui.Services;
using todo_domain_entities;

namespace todo_aspnetmvc_ui.ViewComponents
{
    public class TodoListsViewComponent : ViewComponent
    {
        private readonly ITodoListService service;
        private readonly ILogger<TodoListsViewComponent> logger;

        public TodoListsViewComponent(ILogger<TodoListsViewComponent> logger, ITodoListService service)
        {
            this.service = service;
            this.logger = logger;
        }

        public IViewComponentResult Invoke()
        {
            var todoLists = service.GetListsForUser().ToArray();
            // logger.LogInformation("Found items {0}", JsonSerializer.Serialize(todoLists));
            return View(todoLists);
        }
    }
}

todo-aspnetmvc-ui/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TodoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<div class="container">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TodoList</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted container">
        <div class="container">
            &copy; 2022 - TodoList. <a href="https://github.com/frossu">gh: frossu</a>
        </div>
    </footer>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

todo-aspnetmvc-ui/Views/Shared/_Task.cshtml
@model TaskEntry

<p>
    <span class="text-dark">@Model.Name</span>
    <span class="ml-1">
        <i class="fas fa-clock"></i> @Model.Status.GetDisplayName()
    </span>
    @if (Model.DueDate.HasValue)
    {
        <span><i class="fas fa-calendar-alt"></i> due @Model.DueDate.Value.ToString("dd/MM/yyyy, ddd")</span>
    }
    @* @if (!string.IsNullOrEmpty(Model.Description)) *@
    @* { *@
    <button class="btn btn-outline-dark ml-2" type="button" data-toggle="collapse" data-target=@($"#collapseDescription{Model.Id}") aria-expanded="false">
        Details
    </button>
    @* } *@
    <a class="ml-2" href="@Url.Action("EditTask", "Todo", new {id = Model.Id})">Edit</a>
</p>

<div class="collapse" id=@($"collapseDescription{Model.Id}")>
    <div class="card card-body">
        <div>
            <span><i class="fas fa-calendar-alt"></i> created @Model.CreatedAt.ToString("dd/MM/yyyy, ddd")</span>
        </div>
        @if (string.IsNullOrEmpty(Model.Description))
        {
            <p>No description for the task was provided.</p>
        }
        else
        {
            <p>@Model.Description</p>
        }
    </div>
</div>

todo-aspnetmvc-ui/Views/Shared/_TodoLayout.cshtml
@using Microsoft.CodeAnalysis
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@addTagHelper *, todo_aspnetmvc_ui

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TodoList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/app.css"/>
    <link rel="stylesheet" href="~/lib/font-awesome/dist/css/all.min.css"/>
    @* <link rel="stylesheet" href="~/lib/jquery-ui/dist/themes/blitzer/jquery-ui.min.css"/> *@
</head>
<body>
<div class="d-flex vh-100" id="wrapper">
    <!-- Sidebar-->
    <div class="bg-light border-right position-relative mh-100" id="sidebar-wrapper">
        <div class="sidebar-heading">
            <div class="dropdown">
                <a class="dropdown-toggle text-dark" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @((await UserManager.GetUserAsync(User)).Name)
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    @* <a class="dropdown-item" asp-action="Logout" asp-controller="Account">Log out</a> *@
                    <form id="logout" action="@Url.Action("Logout", "Account")" method="post">
                        <a class="dropdown-item" href="javascript: document.getElementById('logout').submit()">
                            Logout
                        </a>
                    </form>
                </div>
            </div>
        </div>
        @* <vc:todo-lists> </vc:todo-lists> *@
        @await Component.InvokeAsync("TodoLists")
        <form asp-action="CreateList" method="post" class="position-absolute fixed-bottom">
            <button class="list-group-item list-group-item-action bg-light" href="#">Create a new list</button>
        </form>
    </div>
    <!-- Page content wrapper-->
    <div id="page-content-wrapper">
        <!-- Top navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @if (IsSectionDefined("DropdownActions"))
            {
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        @* <li class="nav-item active"> *@
                        @* <a class="nav-link" href="#!"> *@
                        @* Home *@
                        @* <span class="sr-only">(current)</span> *@
                        @* </a> *@
                        @* </li> *@
                        @* <li class="nav-item"> *@
                        @* <a class="nav-link" href="#!">Link</a> *@
                        @* </li> *@
                        <li class="nav-item dropdown">
                            <a class="nav-link" id="navbarDropdown" href="#!" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-bars"></i>
                                <span class="sr-only">Actions</span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                @await RenderSectionAsync("DropdownActions", false)
                            </div>
                        </li>
                    </ul>
                </div>
            }
        </nav>
        <!-- Page content-->
        <div class="container-fluid">
            <main role="main" class="pb-3 pt-3">
                @RenderBody()
            </main>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/jquery-ui/dist/jquery-ui.min.js"></script>
<script src="~/js/app.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>